version: '3'

services:
  redis-1:
    image: redis:6.2
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes-7000.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - redis-1-data:/data
    networks:
      - redis-net

  redis-2:
    image: redis:6.2
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes-7001.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - redis-2-data:/data
    networks:
      - redis-net

  redis-3:
    image: redis:6.2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes-7002.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - redis-3-data:/data
    networks:
      - redis-net

networks:
  redis-net:

volumes:
  redis-1-data:
  redis-2-data:
  redis-3-data: