version: "3.9"

services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.grpc.address=:50051
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.docker=true
      - --providers.docker.network=edge
      - --providers.docker.exposedByDefault=false
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
      - --accesslog=true
      - --metrics.prometheus=true
      - --tracing=true
    ports:
      - "80:80"
      - "8080:8080"
      - "50051:50051"
    environment:
      - DOCKER_API_VERSION=1.40
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - edge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  edge:
    external: true
