version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - --entrypoints.web.address=:80
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --api.dashboard=true
      - --log.level=INFO
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
