http:
  routers:
    config:
      entryPoints: [web]
      rule: "Host(`localhost`) && PathPrefix(`/api/v1/config`)"
      service: svc_config
      middlewares: [cors, strip_config]

    data:
      entryPoints: [web]
      rule: "Host(`localhost`) && PathPrefix(`/api/v1/data`)"
      service: svc_data
      middlewares: [cors, strip_data]

  middlewares:
    cors:
      headers:
        accessControlAllowMethods: ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]
        accessControlAllowHeaders: ["*"]
        accessControlAllowOriginList: ["http://localhost:3000","http://localhost:7777","http://localhost:5173","http://localhost"]
        addVaryHeader: true
    strip_config:
      stripPrefix: { prefixes: ["/api/v1/config"] }
    strip_data:
      stripPrefix: { prefixes: ["/api/v1/data"] }

  services:
    svc_config:
      loadBalancer:
        servers: [{ url: "http://host.docker.internal:3000" }]
    svc_data:
      loadBalancer:
        servers: [{ url: "http://host.docker.internal:7777" }]
