version: "3"

services:
  mssql:
    platform: linux/x86_64
    image: 'mcr.microsoft.com/azure-sql-edge'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Admin123
    volumes:
        - './drive:/var/opt/mssql'