version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.46.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      ## Postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@10.10.0.56:5432/postgres
      ## Add the Postgres database as a data source
      PG_DATABASE_URL: postgres://postgres:postgres@10.10.0.56:5432/postgres
      ## Enable the Hasura console
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## Enable debugging mode (disable in production)
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## Optional: Set an admin secret for security
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data: