version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - jaeger-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "5775:5775/udp"   # UDP for tracing
      - "6831:6831/udp"   # UDP for tracing
      - "6832:6832/udp"   # UDP for tracing
      - "5778:5778"       # UI config API
      - "16686:16686"     # UI
      - "14250:14250"     # gRPC collector
      - "14268:14268"     # HTTP collector
      - "14269:14269"     # Jaeger health check
      - "9411:9411"       # Zipkin compatible endpoint
    networks:
      - jaeger-network
    depends_on:
      - elasticsearch
volumes:
  esdata:

networks:
  jaeger-network:
